import { apiFetch, ApiError } from "./api";
import type { Task } from "@/types/task";
import mockTasks from "@/mock/tasks.json";

interface RawTask {
  id: string;
  title: string;
  department: string;
  owner: string;
  priority: Task["priority"];
  status: Task["status"];
  due_date: string;
  progress: number;
  evidence: boolean;
}

interface RawTaskListResponse {
  count: number;
  tasks: RawTask[];
}

function toTask(raw: RawTask): Task {
  return {
    id: raw.id,
    title: raw.title,
    department: raw.department,
    owner: raw.owner,
    priority: raw.priority,
    status: raw.status,
    dueDate: raw.due_date,
    progress: raw.progress,
    evidence: raw.evidence,
  };
}

/**
 * Returns workflow tasks generated by the backend's Workflow Automation
 * Engine (AI-extracted obligations -> tasks, see POST /tasks/generate).
 *
 * Falls back to bundled mock data if the backend hasn't generated any
 * tasks yet (nothing uploaded) or is unreachable, so pages relying on this
 * service always have something to render.
 */
export async function getTasks(): Promise<Task[]> {
  try {
    const raw = await apiFetch<RawTaskListResponse>("/tasks");
    if (raw.tasks.length > 0) {
      return raw.tasks.map(toTask);
    }
    return mockTasks as Task[];
  } catch (err) {
    if (err instanceof ApiError) {
      console.warn(`Falling back to mock tasks: ${err.message}`);
    } else {
      console.warn("Falling back to mock tasks: backend unreachable");
    }
    return mockTasks as Task[];
  }
}

/** Updates a task's status, progress, evidence flag, and/or owner. */
export async function updateTask(
  id: string,
  updates: Partial<Pick<Task, "status" | "progress" | "evidence" | "owner">>
): Promise<Task> {
  const raw = await apiFetch<RawTask>(`/tasks/${id}`, {
    method: "PATCH",
    body: updates,
  });
  return toTask(raw);
}