"use client";
import * as React from "react";
import { motion } from "framer-motion";
import { Sparkles, AlertTriangle, FileWarning, TrendingUp, ShieldAlert, ArrowRight } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge, riskVariant } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { aiInsights } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

const iconFor: Record<string, { icon: React.ElementType; color: string }> = {
  detection: { icon: Sparkles, color: "text-primary bg-primary-tint" },
  alert: { icon: AlertTriangle, color: "text-danger bg-danger-tint" },
  gap: { icon: FileWarning, color: "text-warning bg-warning-tint" },
  trend: { icon: TrendingUp, color: "text-success bg-success-tint" },
  risk: { icon: ShieldAlert, color: "text-danger bg-danger-tint" },
  recommendation: { icon: Sparkles, color: "text-accent bg-accent-tint" },
};

const typeLabels: Record<string, string> = {
  all: "All", detection: "Detections", alert: "Alerts", gap: "Gaps", trend: "Trends", risk: "Risk", recommendation: "Recommendations",
};

export default function AIInsightsPage() {
  const [tab, setTab] = React.useState("all");
  const filtered = tab === "all" ? aiInsights : aiInsights.filter((i) => i.type === tab);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-bold text-foreground">AI Insights</h1>
        <p className="mt-1 text-sm text-foreground-muted">Continuously generated by RegIntel-AI from your document corpus and workflow signals.</p>
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="w-full overflow-x-auto no-scrollbar sm:w-auto">
          {Object.entries(typeLabels).map(([k, label]) => <TabsTrigger key={k} value={k}>{label}</TabsTrigger>)}
        </TabsList>
      </Tabs>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {filtered.map((insight, i) => {
          const cfg = iconFor[insight.type] ?? iconFor.detection;
          return (
            <motion.div key={insight.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.03 }}>
              <Card className="flex h-full flex-col gap-3 p-5 transition-shadow hover:shadow-[var(--shadow-elevated)]">
                <div className="flex items-center justify-between">
                  <div className={cn("flex h-9 w-9 items-center justify-center rounded-xl", cfg.color)}>
                    <cfg.icon className="h-[18px] w-[18px]" />
                  </div>
                  <Badge variant={riskVariant(insight.severity)}>{insight.severity}</Badge>
                </div>
                <p className="font-display text-[15px] font-semibold leading-snug text-foreground">{insight.title}</p>
                <p className="flex-1 text-[13px] leading-relaxed text-foreground-muted">{insight.detail}</p>
                <Button variant="link" size="sm" className="h-auto justify-start p-0 text-xs">
                  Take action <ArrowRight className="h-3 w-3" />
                </Button>
              </Card>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
